services:
  bus_booking:
    image: venkatasaivinay/bus:v1
    restart: always
    ports:
      - "1111:80"
    volumes:
      - busdata:/usr/share/nginx/html
    networks:
      - busnetwork
    environment:
        username: "sai vinay"
     deploy:
        replicas: 1
        resources:
            limits:
                cpus: "1.5"
                memory: 521M
            reservations:
                cpus: "0.25"
                memory: 256M


  flight_boking:
    image: venkatasaivinay/flight:v1
    restart: always
    ports: 
      - "1122:80"
    volumes:
      - flightdata:/usr/share/nginx/html
    networks:
      - flightnetwork
    deploy:
        replicas: 2
        resources:
            limits:
                cpus: "1.5"
                memory: 521M
            reservations:
                cpus: "0.25"
                memory: 256M
    

volumes:
  busdata:
  flightdata:

networks:
  busnetwork:
    driver: overlay
  flightnetwork:
    driver: overlay

